# -*- coding: utf-8 -*-
"""AI_Customer_Support_+_Ticket_Management.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14IbZejrvFA_ukyrdc5AXOKWW0OWw6UkW
"""

!pip -q install transformers sentence-transformers gradio pandas scikit-learn sqlalchemy torch

import os
import re
import sqlite3
import uuid
import numpy as np
import pandas as pd

from datetime import datetime

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

from sentence_transformers import SentenceTransformer
from transformers import pipeline

import torch
import gradio as gr

os.makedirs("customer_support_project", exist_ok=True)
os.makedirs("customer_support_project/data", exist_ok=True)
os.makedirs("customer_support_project/models", exist_ok=True)

print("Project folders created successfully.")

faq_data = [
    {
        "question": "How can I reset my password?",
        "answer": "You can reset your password by clicking 'Forgot Password' on the login page and following the instructions sent to your registered email.",
        "category": "Account"
    },
    {
        "question": "How do I change my email address?",
        "answer": "Go to Account Settings, select Profile Information, update your email address and verify the new email.",
        "category": "Account"
    },
    {
        "question": "How can I update my phone number?",
        "answer": "Open Account Settings, choose Contact Information and update your phone number. You may be asked to verify the new number.",
        "category": "Account"
    },
    {
        "question": "How can I cancel my order?",
        "answer": "You can cancel an order from the Orders section if it has not already been shipped.",
        "category": "Orders"
    },
    {
        "question": "How can I track my order?",
        "answer": "Open the Orders section in your account and select the order to view its current tracking status.",
        "category": "Orders"
    },
    {
        "question": "My order has not arrived.",
        "answer": "Please check the tracking information first. If the estimated delivery date has passed, create a support ticket so our team can investigate the shipment.",
        "category": "Delivery"
    },
    {
        "question": "How long does delivery take?",
        "answer": "Standard delivery generally takes 3 to 7 business days depending on the destination.",
        "category": "Delivery"
    },
    {
        "question": "How can I return a product?",
        "answer": "Go to Orders, select the product and choose the Return option. Follow the instructions shown on the screen.",
        "category": "Returns"
    },
    {
        "question": "How long does a refund take?",
        "answer": "After a refund is approved, it generally takes 5 to 7 business days for the amount to appear in your bank account.",
        "category": "Refund"
    },
    {
        "question": "I have not received my refund.",
        "answer": "Please verify the refund status in your Orders section. If the expected refund period has passed, create a support ticket.",
        "category": "Refund"
    },
    {
        "question": "What payment methods are supported?",
        "answer": "We support major debit cards, credit cards, UPI and selected online payment methods.",
        "category": "Payment"
    },
    {
        "question": "My payment failed.",
        "answer": "Please verify your payment details and try again. If money was deducted but the order was not created, please create a support ticket.",
        "category": "Payment"
    },
    {
        "question": "I was charged twice.",
        "answer": "If you were charged twice for the same order, please provide the transaction details through a support ticket so the payment can be investigated.",
        "category": "Payment"
    },
    {
        "question": "How do I contact customer support?",
        "answer": "You can contact customer support through this AI support assistant or create a ticket for issues requiring human assistance.",
        "category": "Support"
    },
    {
        "question": "Can I speak with a human agent?",
        "answer": "Yes. Create a support ticket and select the option requesting human assistance. Your ticket will be assigned to the support team.",
        "category": "Support"
    }
]

faq_df = pd.DataFrame(faq_data)

faq_df

faq_df.to_csv(
    "customer_support_project/data/faq_knowledge_base.csv",
    index=False
)

print("FAQ knowledge base saved.")

DB_PATH = "customer_support_project/data/customer_support.db"

conn = sqlite3.connect(DB_PATH)

cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS tickets (
    ticket_id TEXT PRIMARY KEY,
    customer_name TEXT,
    email TEXT,
    message TEXT,
    category TEXT,
    sentiment TEXT,
    priority TEXT,
    status TEXT,
    ai_response TEXT,
    created_at TEXT
)
""")

cursor.execute("""
CREATE TABLE IF NOT EXISTS chat_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ticket_id TEXT,
    user_message TEXT,
    ai_response TEXT,
    timestamp TEXT
)
""")

conn.commit()
conn.close()

print("Database created successfully.")

embedding_model = SentenceTransformer(
    "all-MiniLM-L6-v2"
)

print("Embedding model loaded successfully.")

faq_questions = faq_df["question"].tolist()

faq_embeddings = embedding_model.encode(
    faq_questions,
    convert_to_numpy=True,
    normalize_embeddings=True
)

print("FAQ embeddings created:", faq_embeddings.shape)

def retrieve_faq(query, top_k=3):
    """
    Retrieves the most relevant FAQ documents
    using semantic similarity.
    """

    query_embedding = embedding_model.encode(
        [query],
        convert_to_numpy=True,
        normalize_embeddings=True
    )

    similarities = cosine_similarity(
        query_embedding,
        faq_embeddings
    )[0]

    top_indices = np.argsort(similarities)[::-1][:top_k]

    results = []

    for idx in top_indices:
        results.append({
            "question": faq_df.iloc[idx]["question"],
            "answer": faq_df.iloc[idx]["answer"],
            "category": faq_df.iloc[idx]["category"],
            "score": float(similarities[idx])
        })

    return results

query = "I forgot my login password"

results = retrieve_faq(query, top_k=3)

print("=" * 70)
print("SEMANTIC FAQ RETRIEVAL TEST")
print("=" * 70)

for i, result in enumerate(results, 1):

    print(f"\nResult {i}")
    print("-" * 70)
    print("Question:", result["question"])
    print("Category:", result["category"])
    print("Similarity:", round(result["score"], 3))
    print("Answer:", result["answer"])

sentiment_model = pipeline(
    "sentiment-analysis",
    model="distilbert-base-uncased-finetuned-sst-2-english"
)

print("Sentiment model loaded.")

messages = [
    "I am very happy with your service.",
    "My order is still not delivered and I am very angry."
]

for message in messages:

    result = sentiment_model(message)[0]

    print(message)
    print(result)
    print()

def analyze_sentiment(message):

    result = sentiment_model(message)[0]

    label = result["label"]
    score = result["score"]

    if label == "POSITIVE":
        sentiment = "Positive"
    else:
        sentiment = "Negative"

    return sentiment, round(float(score), 3)

intent_examples = {
    "Account": [
        "forgot password",
        "reset password",
        "change email",
        "change phone number",
        "account problem",
        "login issue",
        "cannot login"
    ],

    "Orders": [
        "cancel order",
        "order cancellation",
        "track my order",
        "order status",
        "wrong order"
    ],

    "Delivery": [
        "order not delivered",
        "delivery is late",
        "where is my package",
        "delivery problem",
        "package hasn't arrived"
    ],

    "Returns": [
        "return product",
        "want to return",
        "return my order",
        "product return",
        "send product back"
    ],

    "Refund": [
        "refund not received",
        "where is my refund",
        "refund problem",
        "money not returned"
    ],

    "Payment": [
        "payment failed",
        "payment problem",
        "charged twice",
        "money deducted",
        "payment unsuccessful"
    ],

    "Support": [
        "contact support",
        "talk to agent",
        "human agent",
        "customer support",
        "need help"
    ]
}

intent_texts = []
intent_labels = []

for intent, examples in intent_examples.items():

    for example in examples:
        intent_texts.append(example)
        intent_labels.append(intent)

intent_vectorizer = TfidfVectorizer(
    stop_words="english",
    ngram_range=(1, 2)
)

intent_matrix = intent_vectorizer.fit_transform(
    intent_texts
)

print("Intent classifier prepared.")

def predict_intent(message):

    message_vector = intent_vectorizer.transform([message])

    similarity = cosine_similarity(
        message_vector,
        intent_matrix
    )[0]

    best_index = similarity.argmax()

    intent = intent_labels[best_index]
    confidence = float(similarity[best_index])

    if confidence < 0.15:
        intent = "General Support"

    return intent, round(confidence, 3)

test_messages = [
    "I forgot my password",
    "My package hasn't arrived",
    "I want my refund",
    "My payment failed",
    "I want to talk to a human"
]

for message in test_messages:

    intent, confidence = predict_intent(message)

    print("Message:", message)
    print("Intent:", intent)
    print("Confidence:", confidence)
    print("-" * 50)

def predict_priority(message, sentiment, intent):

    text = message.lower()

    high_keywords = [
        "fraud",
        "hacked",
        "stolen",
        "urgent",
        "emergency",
        "charged twice",
        "money deducted",
        "account blocked",
        "cannot access",
        "very angry"
    ]

    medium_keywords = [
        "late",
        "failed",
        "problem",
        "issue",
        "not received",
        "incorrect",
        "wrong"
    ]

    if any(word in text for word in high_keywords):
        return "High"

    if sentiment == "Negative" and intent in [
        "Payment",
        "Refund",
        "Account"
    ]:
        return "High"

    if any(word in text for word in medium_keywords):
        return "Medium"

    return "Low"

test_message = "My payment failed and money was deducted twice"

sentiment, sentiment_score = analyze_sentiment(test_message)

intent, intent_confidence = predict_intent(test_message)

priority = predict_priority(
    test_message,
    sentiment,
    intent
)

print("=" * 60)
print("PRIORITY TEST")
print("=" * 60)

print("Message:", test_message)
print("Sentiment:", sentiment)
print("Sentiment Score:", sentiment_score)
print("Intent:", intent)
print("Intent Confidence:", intent_confidence)
print("Priority:", priority)

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

MODEL_NAME = "google/flan-t5-small"

print("Loading tokenizer...")

tokenizer = AutoTokenizer.from_pretrained(
    MODEL_NAME
)

print("Loading FLAN-T5 model...")

model = AutoModelForSeq2SeqLM.from_pretrained(
    MODEL_NAME
)

device = "cuda" if torch.cuda.is_available() else "cpu"

model = model.to(device)

print("=" * 60)
print("LLM MODEL LOADED SUCCESSFULLY")
print("=" * 60)

print("Model:", MODEL_NAME)
print("Device:", device)

def generate_llm_response(prompt, max_new_tokens=120):
    """
    Generate a response using FLAN-T5.
    """

    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=512
    )

    inputs = {
        key: value.to(device)
        for key, value in inputs.items()
    }

    with torch.no_grad():

        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False
        )

    response = tokenizer.decode(
        outputs[0],
        skip_special_tokens=True
    )

    return response.strip()


print("LLM response function created successfully.")

test_prompt = """
Answer the customer using only the information provided.

Knowledge Base:
Standard delivery generally takes 3 to 7 business days depending on the destination.

Customer Question:
How long does delivery take?

Answer:
"""

response = generate_llm_response(
    test_prompt,
    max_new_tokens=80
)

print("=" * 60)
print("LLM TEST")
print("=" * 60)

print(response)

def build_context(results):

    context = ""

    for i, result in enumerate(results, 1):

        context += f"""
FAQ {i}
Question: {result['question']}
Answer: {result['answer']}
Category: {result['category']}
Similarity: {result['score']:.3f}
"""

    return context

def generate_ai_response(user_message):

    retrieved = retrieve_faq(
        user_message,
        top_k=3
    )

    best_result = retrieved[0]

    # Minimum similarity threshold
    if best_result["score"] < 0.25:

        response = (
            "I could not find a specific answer in our "
            "knowledge base. Please create a support ticket "
            "so that our support team can investigate your issue."
        )

        return response, retrieved

    context = build_context(retrieved)

    prompt = f"""
You are a professional customer support assistant.

Answer the customer's question using ONLY the information
provided in the knowledge base.

Knowledge Base:
{context}

Customer Question:
{user_message}

Rules:
1. Be polite and professional.
2. Keep the answer short and clear.
3. Do not invent information.
4. Do not use information outside the knowledge base.
5. If the information is insufficient, tell the customer
   to create a support ticket.

Answer:
"""

    response = generate_llm_response(
        prompt,
        max_new_tokens=120
    )

    return response, retrieved

message = "My order has not arrived yet"

response, retrieved = generate_ai_response(
    message
)

print("=" * 70)
print("CUSTOMER MESSAGE")
print("=" * 70)

print(message)

print("\n" + "=" * 70)
print("AI SUPPORT RESPONSE")
print("=" * 70)

print(response)

print("\n" + "=" * 70)
print("RETRIEVED KNOWLEDGE")
print("=" * 70)

for i, item in enumerate(retrieved, 1):

    print(f"\nResult {i}")
    print("-" * 70)

    print("Question:", item["question"])
    print("Category:", item["category"])
    print("Similarity:", round(item["score"], 3))
    print("Answer:", item["answer"])

def create_ticket(customer_name, email, message):

    conn = None

    try:

        # ==================================================
        # 1. GENERATE TICKET ID
        # ==================================================

        ticket_id = "TKT-" + uuid.uuid4().hex[:8].upper()

        # ==================================================
        # 2. SENTIMENT ANALYSIS
        # ==================================================

        sentiment, sentiment_score = analyze_sentiment(
            message
        )

        # ==================================================
        # 3. INTENT CLASSIFICATION
        # ==================================================

        intent, intent_confidence = predict_intent(
            message
        )

        # ==================================================
        # 4. PRIORITY PREDICTION
        # ==================================================

        priority = predict_priority(
            message,
            sentiment,
            intent
        )

        # ==================================================
        # 5. AI RESPONSE USING RAG
        # ==================================================

        ai_response, retrieved = generate_ai_response(
            message
        )

        # ==================================================
        # 6. CREATED TIME
        # ==================================================

        created_at = datetime.now().strftime(
            "%Y-%m-%d %H:%M:%S"
        )

        # ==================================================
        # 7. CONNECT DATABASE
        # ==================================================

        conn = sqlite3.connect(
            DB_PATH
        )

        cursor = conn.cursor()

        # ==================================================
        # 8. INSERT TICKET
        # ==================================================

        cursor.execute(
            """
            INSERT INTO tickets (
                ticket_id,
                customer_name,
                email,
                message,
                category,
                sentiment,
                priority,
                status,
                ai_response,
                created_at
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                ticket_id,
                customer_name,
                email,
                message,
                intent,
                sentiment,
                priority,
                "Open",
                ai_response,
                created_at
            )
        )

        # ==================================================
        # 9. SAVE CHAT HISTORY
        # ==================================================

        cursor.execute(
            """
            INSERT INTO chat_history (
                ticket_id,
                user_message,
                ai_response,
                timestamp
            )
            VALUES (?, ?, ?, ?)
            """,
            (
                ticket_id,
                message,
                ai_response,
                created_at
            )
        )

        # ==================================================
        # 10. COMMIT DATABASE
        # ==================================================

        conn.commit()

        # ==================================================
        # 11. VERIFY TICKET
        # ==================================================

        cursor.execute(
            "SELECT COUNT(*) FROM tickets"
        )

        count = cursor.fetchone()[0]

        print(
            "Database ticket count:",
            count
        )

        # ==================================================
        # 12. RETURN RESULT
        # ==================================================

        return {
            "ticket_id": ticket_id,
            "category": intent,
            "sentiment": sentiment,
            "priority": priority,
            "ai_response": ai_response,
            "created_at": created_at
        }

    except Exception as e:

        if conn is not None:
            conn.rollback()

        print("=" * 60)
        print("ERROR WHILE CREATING TICKET")
        print("=" * 60)

        print(
            "Error Type:",
            type(e).__name__
        )

        print(
            "Error:",
            str(e)
        )

        return None

    finally:

        if conn is not None:
            conn.close()

ticket = create_ticket(
    customer_name="Piyush",
    email="piyush@example.com",
    message="My order has not arrived and I am very frustrated."
)

print("=" * 60)
print("TICKET CREATION TEST")
print("=" * 60)

if ticket is not None:

    print("Ticket created successfully!\n")

    for key, value in ticket.items():

        print(
            f"{key}: {value}"
        )

else:

    print("❌ Ticket creation failed.")
    print("Check the error message printed above.")

def get_all_tickets():

    conn = sqlite3.connect(
        DB_PATH
    )

    df = pd.read_sql_query(
        """
        SELECT *
        FROM tickets
        ORDER BY created_at DESC
        """,
        conn
    )

    conn.close()

    return df


tickets_df = get_all_tickets()

print(
    "Total tickets:",
    len(tickets_df)
)

display(tickets_df)

def update_ticket_status(
    ticket_id,
    new_status
):

    allowed_status = [
        "Open",
        "In Progress",
        "Resolved",
        "Closed"
    ]

    if new_status not in allowed_status:

        return "Invalid status."

    conn = sqlite3.connect(
        DB_PATH
    )

    cursor = conn.cursor()

    cursor.execute(
        """
        UPDATE tickets
        SET status = ?
        WHERE ticket_id = ?
        """,
        (
            new_status,
            ticket_id
        )
    )

    conn.commit()

    rows_updated = cursor.rowcount

    conn.close()

    if rows_updated == 0:

        return "Ticket not found."

    return (
        f"Ticket {ticket_id} "
        f"updated to {new_status}."
    )

df = get_all_tickets()

df[["ticket_id", "status", "priority", "category"]]

df = get_all_tickets()

print(
    "Total tickets:",
    len(df)
)

if df.empty:

    print(
        "❌ No tickets found."
    )

    print(
        "Run the ticket creation test first."
    )

else:

    ticket_id = str(
        df.iloc[0]["ticket_id"]
    )

    print(
        "Selected Ticket:",
        ticket_id
    )

    result = update_ticket_status(
        ticket_id,
        "In Progress"
    )

    print(
        "\nUpdate Result:"
    )

    print(result)

    updated_df = get_all_tickets()

    print(
        "\nUpdated Ticket:"
    )

    display(
        updated_df[
            updated_df["ticket_id"] == ticket_id
        ][
            [
                "ticket_id",
                "customer_name",
                "category",
                "priority",
                "status"
            ]
        ]
    )

# LOAD ALL TICKETS

df = get_all_tickets()

print("Total tickets:", len(df))

display(
    df[
        [
            "ticket_id",
            "customer_name",
            "category",
            "sentiment",
            "priority",
            "status"
        ]
    ]
)

# UPDATE TICKET STATUS

df = get_all_tickets()

ticket_id = str(df.iloc[-1]["ticket_id"])

print("Ticket selected:", ticket_id)

result = update_ticket_status(
    ticket_id,
    "In Progress"
)

print(result)

def search_tickets(keyword):

    conn = sqlite3.connect(DB_PATH)

    query = """
    SELECT *
    FROM tickets
    WHERE
        ticket_id LIKE ?
        OR customer_name LIKE ?
        OR email LIKE ?
        OR message LIKE ?
        OR category LIKE ?
    ORDER BY created_at DESC
    """

    pattern = f"%{keyword}%"

    df = pd.read_sql_query(
        query,
        conn,
        params=(
            pattern,
            pattern,
            pattern,
            pattern,
            pattern
        )
    )

    conn.close()

    return df

search_result = search_tickets(
    "order"
)

print(
    "Search Results:"
)

display(search_result)

def ticket_statistics():

    conn = sqlite3.connect(DB_PATH)

    total = pd.read_sql_query(
        "SELECT COUNT(*) AS count FROM tickets",
        conn
    ).iloc[0]["count"]

    open_tickets = pd.read_sql_query(
        """
        SELECT COUNT(*) AS count
        FROM tickets
        WHERE status = 'Open'
        """,
        conn
    ).iloc[0]["count"]

    high_priority = pd.read_sql_query(
        """
        SELECT COUNT(*) AS count
        FROM tickets
        WHERE priority = 'High'
        """,
        conn
    ).iloc[0]["count"]

    resolved = pd.read_sql_query(
        """
        SELECT COUNT(*) AS count
        FROM tickets
        WHERE status = 'Resolved'
        """,
        conn
    ).iloc[0]["count"]

    conn.close()

    return {
        "Total Tickets": int(total),
        "Open Tickets": int(open_tickets),
        "High Priority": int(high_priority),
        "Resolved Tickets": int(resolved)
    }

stats = ticket_statistics()

print("=" * 60)
print("TICKET STATISTICS")
print("=" * 60)

for key, value in stats.items():

    print(
        f"{key}: {value}"
    )

sample_tickets = [
    (
        "Rahul",
        "rahul@gmail.com",
        "I forgot my password and cannot login."
    ),
    (
        "Ankit",
        "ankit@gmail.com",
        "My order has not arrived yet."
    ),
    (
        "Neha",
        "neha@gmail.com",
        "I want to return my product."
    ),
    (
        "Aman",
        "aman@gmail.com",
        "My payment failed."
    ),
    (
        "Priya",
        "priya@gmail.com",
        "I have not received my refund."
    ),
    (
        "Rohit",
        "rohit@gmail.com",
        "I was charged twice for my order."
    ),
    (
        "Sneha",
        "sneha@gmail.com",
        "I want to talk to a human support agent."
    )
]

existing_tickets = get_all_tickets()

if existing_tickets.empty:

    print(
        "Creating sample tickets..."
    )

    for name, email, message in sample_tickets:

        create_ticket(
            name,
            email,
            message
        )

    print(
        "Sample tickets created successfully."
    )

else:

    print(
        f"Database already contains "
        f"{len(existing_tickets)} tickets."
    )

    print(
        "Sample tickets were not duplicated."
    )

df = get_all_tickets()

pd.set_option(
    "display.max_colwidth",
    100
)

print(
    "Total Tickets:",
    len(df)
)

display(df)

df = get_all_tickets()

category_counts = (
    df["category"]
    .value_counts()
    .reset_index()
)

category_counts.columns = [
    "Category",
    "Tickets"
]

display(category_counts)

priority_counts = (
    df["priority"]
    .value_counts()
    .reset_index()
)

priority_counts.columns = [
    "Priority",
    "Tickets"
]

display(priority_counts)

sentiment_counts = (
    df["sentiment"]
    .value_counts()
    .reset_index()
)

sentiment_counts.columns = [
    "Sentiment",
    "Tickets"
]

display(sentiment_counts)

import matplotlib.pyplot as plt

category_counts = (
    df["category"]
    .value_counts()
)

plt.figure(figsize=(10, 5))

category_counts.plot(
    kind="bar"
)

plt.title("Tickets by Category")
plt.xlabel("Category")
plt.ylabel("Number of Tickets")

plt.xticks(rotation=45)

plt.tight_layout()

plt.show()

priority_counts = (
    df["priority"]
    .value_counts()
)

plt.figure(figsize=(7, 5))

priority_counts.plot(
    kind="bar"
)

plt.title("Tickets by Priority")
plt.xlabel("Priority")
plt.ylabel("Number of Tickets")

plt.tight_layout()

plt.show()

sentiment_counts = (
    df["sentiment"]
    .value_counts()
)

plt.figure(figsize=(7, 5))

sentiment_counts.plot(
    kind="bar"
)

plt.title("Customer Sentiment")
plt.xlabel("Sentiment")
plt.ylabel("Number of Tickets")

plt.tight_layout()

plt.show()

conn = sqlite3.connect(DB_PATH)

query = """
SELECT
    category,
    COUNT(*) AS total_tickets
FROM tickets
GROUP BY category
ORDER BY total_tickets DESC;
"""

sql_result = pd.read_sql_query(
    query,
    conn
)

conn.close()

sql_result

conn = sqlite3.connect(DB_PATH)

query = """
SELECT
    ticket_id,
    customer_name,
    category,
    priority,
    status,
    created_at
FROM tickets
WHERE status != 'Resolved'
AND status != 'Closed'
ORDER BY
    CASE
        WHEN priority = 'High' THEN 1
        WHEN priority = 'Medium' THEN 2
        ELSE 3
    END,
    created_at DESC;
"""

unresolved = pd.read_sql_query(
    query,
    conn
)

conn.close()

unresolved

def customer_support(
    name,
    email,
    message
):

    # -------------------------
    # INPUT VALIDATION
    # -------------------------

    if not name or not name.strip():
        name = "Guest"

    if not email or not email.strip():
        email = "Not Provided"

    if not message or not message.strip():

        return """
### ⚠️ Missing Message

Please enter your question or problem.
"""

    # -------------------------
    # CREATE TICKET
    # -------------------------

    result = create_ticket(
        customer_name=name,
        email=email,
        message=message
    )

    # -------------------------
    # ERROR HANDLING
    # -------------------------

    if result is None:

        return """
### ❌ Ticket Creation Failed

We could not create your support ticket.

Please try again.
"""

    # -------------------------
    # OUTPUT
    # -------------------------

    output = f"""
### 🤖 AI Customer Support

**Ticket ID:** `{result['ticket_id']}`

**Category:** {result['category']}

**Sentiment:** {result['sentiment']}

**Priority:** {result['priority']}

**Status:** Open

---

### 💬 AI Response

{result['ai_response']}

---

✅ Your issue has been successfully recorded
in the support system.
"""

    return output

with gr.Blocks(
    title="AI Customer Support System"
) as customer_app:

    gr.Markdown(
        """
        # 🤖 AI Customer Support Assistant

        Ask a question or report a problem.

        The AI will analyze your request, retrieve
        relevant information and create a support ticket.
        """
    )

    with gr.Row():

        name = gr.Textbox(
            label="Customer Name",
            placeholder="Enter your name"
        )

        email = gr.Textbox(
            label="Email",
            placeholder="Enter your email"
        )

    message = gr.Textbox(
        label="Your Question / Problem",
        placeholder="Example: My order has not arrived yet...",
        lines=5
    )

    submit = gr.Button(
        "Submit Request",
        variant="primary"
    )

    output = gr.Markdown()

    submit.click(
        fn=customer_support,
        inputs=[
            name,
            email,
            message
        ],
        outputs=output
    )

customer_app.launch(
    share=True
)

def admin_dashboard():

    df = get_all_tickets()

    if df.empty:

        return (
            "No tickets available.",
            pd.DataFrame()
        )

    stats = ticket_statistics()

    summary = f"""
# 📊 Customer Support Dashboard

### Total Tickets
{stats['Total Tickets']}

### Open Tickets
{stats['Open Tickets']}

### High Priority Tickets
{stats['High Priority']}

### Resolved Tickets
{stats['Resolved Tickets']}
"""

    return summary, df


def admin_search(keyword):

    if not keyword or not keyword.strip():

        return get_all_tickets()

    return search_tickets(
        keyword
    )


def admin_update_status(
    ticket_id,
    new_status
):

    result = update_ticket_status(
        ticket_id,
        new_status
    )

    return result

with gr.Blocks(
    title="Customer Support Admin Dashboard"
) as admin_app:

    gr.Markdown(
        """
        # 📊 AI Customer Support
        ## Admin Dashboard
        """
    )

    # ==================================================
    # SUMMARY
    # ==================================================

    summary = gr.Markdown()

    refresh = gr.Button(
        "🔄 Refresh Dashboard"
    )

    tickets = gr.Dataframe(
        interactive=False
    )

    refresh.click(
        fn=admin_dashboard,
        inputs=[],
        outputs=[
            summary,
            tickets
        ]
    )

    admin_app.load(
        fn=admin_dashboard,
        inputs=[],
        outputs=[
            summary,
            tickets
        ]
    )

    # ==================================================
    # SEARCH
    # ==================================================

    gr.Markdown(
        "## 🔎 Search Tickets"
    )

    with gr.Row():

        search_box = gr.Textbox(
            label="Search",
            placeholder="Ticket ID, name, email, category..."
        )

        search_button = gr.Button(
            "Search"
        )

    search_results = gr.Dataframe(
        interactive=False
    )

    search_button.click(
        fn=admin_search,
        inputs=search_box,
        outputs=search_results
    )

    # ==================================================
    # UPDATE STATUS
    # ==================================================

    gr.Markdown(
        "## 🔄 Update Ticket Status"
    )

    with gr.Row():

        ticket_id_input = gr.Textbox(
            label="Ticket ID",
            placeholder="Example: TKT-1234ABCD"
        )

        status_dropdown = gr.Dropdown(
            choices=[
                "Open",
                "In Progress",
                "Resolved",
                "Closed"
            ],
            label="New Status"
        )

        update_button = gr.Button(
            "Update Status"
        )

    status_output = gr.Markdown()

    update_button.click(
        fn=admin_update_status,
        inputs=[
            ticket_id_input,
            status_dropdown
        ],
        outputs=status_output
    )


admin_app.launch(
    share=True
)



df = get_all_tickets()

df.to_csv(
    "customer_support_project/data/tickets_export.csv",
    index=False
)

print("Tickets exported successfully.")

print("""
====================================================
 AI CUSTOMER SUPPORT + TICKET MANAGEMENT SYSTEM
====================================================

Technologies:
- Python
- NLP
- Machine Learning
- RAG
- LLM
- Sentence Transformers
- Scikit-learn
- SQLite / SQL
- Gradio
- Pandas

Features:
✓ AI Customer Support
✓ FAQ Knowledge Base
✓ Semantic RAG Retrieval
✓ Sentiment Analysis
✓ Intent Classification
✓ Automatic Priority Detection
✓ Ticket Creation
✓ Ticket Status Management
✓ SQL Database
✓ Ticket Search
✓ Admin Dashboard
✓ Analytics
✓ CSV Export

====================================================
""")

